/* eslint-disable @typescript-eslint/no-non-null-assertion */
import {
    ArgumentsHost,
    BadRequestException,
    HttpException,
    HttpStatus,
    NotFoundException,
    ServiceUnavailableException,
} from '@nestjs/common';
import { HttpAdapterHost } from '@nestjs/core';

import { TELEMETRY_MAX_STACK_LENGTH } from '../../../domain/constants/telemetry.constants';
import { DomainError } from '../../../domain/errors/domain.error';
import type { TelemetryEvent } from '../../../domain/models/telemetry.models';
import { getTelemetry, runWithTelemetry } from '../../../infrastructure/telemetry/telemetry.context';
import { AllExceptionsFilter } from '../all-exceptions.filter';

/**
 * Consistent error-envelope shape asserted at the `reply(...)` boundary.
 */
interface ErrorEnvelope {
    statusCode: number;
    code: string;
    message: string | string[];
    error: string;
    details?: object;
    timestamp: string;
    path: string;
    requestId: string;
}

/**
 * Stand-in for a feature domain error, so the specs pin the `cause.code` →
 * envelope `code` half of the contract without depending on a feature.
 */
class CodedDomainError extends DomainError {
    constructor(code: string, message = 'Domain failure') {
        super(code, message);
    }
}

const REQUEST_PATH = '/api/v1/resource';
const REQUEST_ID = 'req-1234';

/** Code the filter publishes for a failure the client caused with no domain code. */
const GENERIC_CLIENT_ERROR_CODE = 'CLIENT_ERROR';

/** Code the filter publishes for a failure the server caused with no domain code. */
const GENERIC_SERVER_ERROR_CODE = 'SERVER_ERROR';

/** RFC 4122 shape of a correlation id generated by the filter. */
// eslint-disable-next-line security/detect-unsafe-regex
const UUID_PATTERN = /^[\da-f]{8}(?:-[\da-f]{4}){3}-[\da-f]{12}$/;

/**
 * Builds a fake `ArgumentsHost` from `jest.fn()` mocks whose HTTP context hands
 * back the fixture request/response — mirrors the decorator spec's fake
 * `ExecutionContext`.
 */
const hostFor = (
    request: unknown,
    response: unknown,
): ArgumentsHost => {
    const mockGetRequest = jest.fn().mockReturnValue(request);
    const mockGetResponse = jest.fn().mockReturnValue(response);
    const mockSwitchToHttp = jest
        .fn()
        .mockReturnValue({ getRequest: mockGetRequest, getResponse: mockGetResponse });

    return {
        switchToHttp: mockSwitchToHttp,
    } as unknown as ArgumentsHost;
};

describe('AllExceptionsFilter', () => {
    const request = { url: REQUEST_PATH, headers: { 'x-request-id': REQUEST_ID } };
    const response = {};

    let mockReply: jest.Mock;
    let mockGetRequestUrl: jest.Mock;
    let mockHttpAdapterHost: HttpAdapterHost;
    let sut: AllExceptionsFilter;

    /**
     * Runs the filter inside a real telemetry scope, so the fields it enriches
     * are observable, and hands back the accumulated event.
     */
    const catchInTelemetryScope = (
        exception: unknown,
        host: ArgumentsHost = hostFor(request, response),
    ): Partial<TelemetryEvent> => runWithTelemetry({}, () => {
        sut.catch(exception, host);

        return getTelemetry() ?? {};
    });

    beforeEach(() => {
        jest.clearAllMocks();

        mockReply = jest.fn();
        mockGetRequestUrl = jest.fn().mockReturnValue(REQUEST_PATH);

        const httpAdapter: jest.Mocked<Pick<
            HttpAdapterHost['httpAdapter'],
            'getRequestUrl' | 'reply'
        >> = {
            getRequestUrl: mockGetRequestUrl,
            reply: mockReply,
        };

        mockHttpAdapterHost = { httpAdapter } as unknown as HttpAdapterHost;

        sut = new AllExceptionsFilter(mockHttpAdapterHost);
    });

    afterEach(() => {
        jest.restoreAllMocks();
    });

    it('formats an HttpException into an envelope preserving status code and message', () => {
        sut.catch(new NotFoundException('Item missing'), hostFor(request, response));

        expect(mockReply).toHaveBeenCalledTimes(1);
        const [replyResponse, envelope, statusCode] = mockReply.mock.calls[0] as [
            unknown,
            ErrorEnvelope,
            number,
        ];

        expect(replyResponse).toBe(response);
        expect(statusCode).toBe(404);
        expect(envelope).toEqual({
            statusCode: 404,
            code: GENERIC_CLIENT_ERROR_CODE,
            message: 'Item missing',
            error: 'Not Found',
            path: REQUEST_PATH,
            timestamp: expect.any(String),
            requestId: REQUEST_ID,
        });
    });

    it('preserves the validation message array from a BadRequestException', () => {
        const validationMessages = ['name must be a string', 'age must be an integer'];

        sut.catch(new BadRequestException(validationMessages), hostFor(request, response));

        expect(mockReply).toHaveBeenCalledTimes(1);
        const [replyResponse, envelope, statusCode] = mockReply.mock.calls[0] as [
            unknown,
            ErrorEnvelope,
            number,
        ];

        expect(replyResponse).toBe(response);
        expect(statusCode).toBe(400);
        expect(envelope).toEqual({
            statusCode: 400,
            code: GENERIC_CLIENT_ERROR_CODE,
            message: validationMessages,
            error: 'Bad Request',
            path: REQUEST_PATH,
            timestamp: expect.any(String),
            requestId: REQUEST_ID,
        });
        expect(Array.isArray(envelope.message)).toBe(true);
    });

    it('falls back to a generic error label for a status with no canonical name', () => {
        sut.catch(new HttpException('odd failure', 599), hostFor(request, response));

        const [, envelope, statusCode] = mockReply.mock.calls[0] as [
            unknown,
            ErrorEnvelope,
            number,
        ];

        expect(statusCode).toBe(599);
        expect(envelope.error).toBe('Error');
        expect(envelope.code).toBe(GENERIC_SERVER_ERROR_CODE);
        expect(envelope.requestId).toBe(REQUEST_ID);
    });

    it('returns a generic 500 for an unexpected error without leaking internal details', () => {
        const error = new Error('secret db connection string leaked');

        sut.catch(error, hostFor(request, response));

        expect(mockReply).toHaveBeenCalledTimes(1);
        const [replyResponse, envelope, statusCode] = mockReply.mock.calls[0] as [
            unknown,
            ErrorEnvelope,
            number,
        ];

        expect(replyResponse).toBe(response);
        expect(statusCode).toBe(500);
        expect(envelope).toEqual({
            statusCode: 500,
            code: GENERIC_SERVER_ERROR_CODE,
            message: 'Internal server error',
            error: 'Internal Server Error',
            path: REQUEST_PATH,
            timestamp: expect.any(String),
            requestId: REQUEST_ID,
        });
        expect(JSON.stringify(envelope)).not.toContain('secret db connection string');
    });

    it('replies as usual outside a telemetry scope, where the enrichment is a no-op', () => {
        sut.catch(new NotFoundException('Item missing'), hostFor(request, response));

        expect(mockReply).toHaveBeenCalledTimes(1);
        expect(getTelemetry()).toBeUndefined();
    });

    describe('telemetry event enrichment', () => {
        it('always adds the type, the code and the internal message of the failure', () => {
            const domainError = new CodedDomainError('SERVICE_NOT_FOUND', 'Service missing');

            const event = catchInTelemetryScope(
                new NotFoundException('Item missing', { cause: domainError }),
            );

            expect(event).toMatchObject({
                'error.type': 'NotFoundException',
                'error.code': 'SERVICE_NOT_FOUND',
                'error.message': 'Item missing',
            });
        });

        it('records the internal message of an unexpected error, which the client never sees', () => {
            const event = catchInTelemetryScope(new Error('secret db connection string leaked'));

            expect(event['error.type']).toBe('Error');
            expect(event['error.code']).toBe(GENERIC_SERVER_ERROR_CODE);
            expect(event['error.message']).toBe('secret db connection string leaked');
        });

        it('records the primitive type and the stringified value of a non-Error thrown value', () => {
            const event = catchInTelemetryScope('just a string');

            expect(event['error.type']).toBe('string');
            expect(event['error.code']).toBe(GENERIC_SERVER_ERROR_CODE);
            expect(event['error.message']).toBe('just a string');
            expect(Object.keys(event)).not.toContain('error.stack');
            expect(Object.keys(event)).not.toContain('error.cause_chain');
        });

        describe('stack', () => {
            it('adds the stack of a 5xx failure', () => {
                const error = new Error('boom');

                const event = catchInTelemetryScope(error);

                expect(event['error.stack']).toBe(error.stack);
            });

            it('appends the stack of every chained cause on a 5xx failure', () => {
                const original = new Error('ECONNREFUSED 127.0.0.1:2375');
                const exception = new ServiceUnavailableException('Could not reach the daemon', {
                    cause: original,
                });

                const stack = catchInTelemetryScope(exception)['error.stack']!;

                expect(stack).toContain(exception.stack!);
                expect(stack).toContain('Caused by:');
                expect(stack).toContain('ECONNREFUSED 127.0.0.1:2375');
            });

            it('follows the whole cause chain, so the root failure is never lost', () => {
                const root = new Error('socket hang up');
                const domainError = new CodedDomainError('PROVIDER_UNAVAILABLE');

                Object.defineProperty(domainError, 'cause', { value: root });

                const exception = new ServiceUnavailableException(domainError.message, {
                    cause: domainError,
                });

                // Short stacks, so the assertion is about following the chain and
                // never about the cap the filter applies to the joined result.
                root.stack = 'Error: socket hang up';
                domainError.stack = 'CodedDomainError: Domain failure';
                exception.stack = 'ServiceUnavailableException: Domain failure';

                const stack = catchInTelemetryScope(exception)['error.stack']!;

                expect(stack).toBe(
                    'ServiceUnavailableException: Domain failure\n'
                    + 'Caused by: CodedDomainError: Domain failure\n'
                    + 'Caused by: Error: socket hang up',
                );
                expect(stack.match(/Caused by:/g)).toHaveLength(2);
                expect(stack).not.toContain('truncated');
            });

            it('stops on a cyclic cause chain', () => {
                const first = new Error('first');
                const second = new Error('second', { cause: first });

                Object.defineProperty(first, 'cause', { value: second });

                const stack = catchInTelemetryScope(second)['error.stack']!;

                expect(stack).toContain('first');
                expect(stack.match(/Caused by:/g)).toHaveLength(1);
            });

            it('leaves a stack shorter than the cap unchanged, with no truncation marker', () => {
                const error = new Error('boom');

                error.stack = `Error: boom\n${'    at frame\n'.repeat(10)}`;

                const stack = catchInTelemetryScope(error)['error.stack']!;

                expect(stack).toBe(error.stack);
                expect(stack).not.toContain('truncated');
            });

            it('leaves a stack of exactly the cap unchanged, with no truncation marker', () => {
                const error = new Error('boom');

                error.stack = 'a'.repeat(TELEMETRY_MAX_STACK_LENGTH);

                const stack = catchInTelemetryScope(error)['error.stack']!;

                expect(stack).toBe(error.stack);
                expect(stack.length).toBe(TELEMETRY_MAX_STACK_LENGTH);
                expect(stack).not.toContain('truncated');
            });

            it('caps a stack one character over the limit', () => {
                const error = new Error('boom');

                error.stack = 'b'.repeat(TELEMETRY_MAX_STACK_LENGTH + 1);

                const stack = catchInTelemetryScope(error)['error.stack']!;
                const removed = Number(/truncated (\d+) characters/.exec(stack)![1]);
                const marker = `\n… [truncated ${removed} characters]`;

                expect(stack.length).toBe(TELEMETRY_MAX_STACK_LENGTH);
                expect(stack).toBe(
                    'b'.repeat(TELEMETRY_MAX_STACK_LENGTH - marker.length) + marker,
                );
                expect(removed).toBe(error.stack.length - (TELEMETRY_MAX_STACK_LENGTH - marker.length));
            });

            it('accounts for the marker growing as the removed count gains a digit', () => {
                const error = new Error('boom');
                // The overflow is two digits long, but the marker it needs pushes the
                // removed count to three, so the marker has to be measured again.
                const overflow = 80;

                error.stack = 'c'.repeat(TELEMETRY_MAX_STACK_LENGTH + overflow);

                const stack = catchInTelemetryScope(error)['error.stack']!;
                const removed = Number(/truncated (\d+) characters/.exec(stack)![1]);
                const marker = `\n… [truncated ${removed} characters]`;

                expect(String(overflow)).toHaveLength(2);
                expect(String(removed)).toHaveLength(3);
                expect(stack.length).toBe(TELEMETRY_MAX_STACK_LENGTH);
                expect(removed).toBe(error.stack.length - (TELEMETRY_MAX_STACK_LENGTH - marker.length));
                expect(stack.endsWith(marker)).toBe(true);
            });

            it('falls back to the name and message of an exception carrying no stack', () => {
                const error = new Error('boom');

                delete error.stack;

                const event = catchInTelemetryScope(error);

                expect(event['error.stack']).toBe('Error: boom');
            });

            it('falls back to the name and message of a chained cause carrying no stack', () => {
                const root = new Error('socket hang up');
                const exception = new ServiceUnavailableException('Could not reach the daemon', {
                    cause: root,
                });

                delete root.stack;
                exception.stack = 'ServiceUnavailableException: Could not reach the daemon';

                const stack = catchInTelemetryScope(exception)['error.stack']!;

                expect(stack).toBe(
                    'ServiceUnavailableException: Could not reach the daemon\nCaused by: Error: socket hang up',
                );
            });

            it('caps a stack longer than the limit, keeping its first characters', () => {
                const error = new Error('boom');
                const head = 'Error: boom\n    at the frame that carries the failure\n';

                error.stack = head + 'x'.repeat(TELEMETRY_MAX_STACK_LENGTH * 2);

                const stack = catchInTelemetryScope(error)['error.stack']!;

                expect(stack.length).toBe(TELEMETRY_MAX_STACK_LENGTH);
                expect(stack.startsWith(head)).toBe(true);
                expect(stack).toMatch(/\n… \[truncated \d+ characters]$/);
            });

            it('reports how many characters the truncation removed', () => {
                const error = new Error('boom');

                error.stack = 'y'.repeat(TELEMETRY_MAX_STACK_LENGTH + 500);

                const stack = catchInTelemetryScope(error)['error.stack']!;
                const removed = Number(/truncated (\d+) characters/.exec(stack)![1]);
                const marker = `\n… [truncated ${removed} characters]`;

                expect(removed).toBe(error.stack.length - (TELEMETRY_MAX_STACK_LENGTH - marker.length));
                expect(stack).toBe(
                    error.stack.slice(0, TELEMETRY_MAX_STACK_LENGTH - marker.length) + marker,
                );
            });

            it('caps the joined cause chain as a whole', () => {
                const root = new Error('root');
                const exception = new ServiceUnavailableException('outer', { cause: root });

                root.stack = 'z'.repeat(TELEMETRY_MAX_STACK_LENGTH);
                exception.stack = `Error: outer\n${'w'.repeat(TELEMETRY_MAX_STACK_LENGTH)}`;

                const stack = catchInTelemetryScope(exception)['error.stack']!;

                expect(stack.length).toBe(TELEMETRY_MAX_STACK_LENGTH);
                expect(stack.startsWith('Error: outer\n')).toBe(true);
                expect(stack).toContain('truncated');
            });

            it('adds no stack for a 4xx failure, which the server did not cause', () => {
                const exception = new NotFoundException('Item missing');

                const event = catchInTelemetryScope(exception);

                expect(exception.stack).toBeDefined();
                expect(Object.keys(event)).not.toContain('error.stack');
            });

            it('adds no stack for a 4xx failure carrying a cause either', () => {
                const event = catchInTelemetryScope(
                    new BadRequestException('nope', { cause: new Error('boom') }),
                );

                expect(Object.keys(event)).not.toContain('error.stack');
            });

            it('keeps the stack out of the client envelope', () => {
                catchInTelemetryScope(
                    new ServiceUnavailableException('Could not reach the daemon', {
                        cause: new Error('ECONNREFUSED 127.0.0.1:2375'),
                    }),
                );

                const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

                expect(JSON.stringify(envelope)).not.toContain('ECONNREFUSED');
                expect(JSON.stringify(envelope)).not.toContain('Caused by:');
            });
        });

        describe('cause chain', () => {
            it('adds the type of every chained cause, from the nearest to the root', () => {
                const root = new Error('socket hang up');
                const domainError = new CodedDomainError('PROVIDER_UNAVAILABLE');

                Object.defineProperty(domainError, 'cause', { value: root });

                const event = catchInTelemetryScope(
                    new ServiceUnavailableException(domainError.message, { cause: domainError }),
                );

                expect(event['error.cause_chain']).toEqual(['CodedDomainError', 'Error']);
            });

            it('adds the cause chain of a 4xx failure too', () => {
                const event = catchInTelemetryScope(
                    new NotFoundException('missing', { cause: new Error('boom') }),
                );

                expect(event['error.cause_chain']).toEqual(['Error']);
            });

            it('adds no cause chain when the failure has no cause', () => {
                const event = catchInTelemetryScope(new NotFoundException('Item missing'));

                expect(Object.keys(event)).not.toContain('error.cause_chain');
            });

            it('stops on a cyclic cause chain', () => {
                const first = new Error('first');
                const second = new Error('second', { cause: first });

                Object.defineProperty(first, 'cause', { value: second });

                const event = catchInTelemetryScope(second);

                expect(event['error.cause_chain']).toEqual(['Error']);
            });
        });
    });

    describe('structured exception bodies', () => {
        it('keeps an object payload under details instead of dropping it', () => {
            const readiness = {
                status: 'error',
                dependencies: [
                    { name: 'database', status: 'up' },
                    { name: 'docker', status: 'down' },
                ],
            };

            sut.catch(new ServiceUnavailableException(readiness), hostFor(request, response));

            const [, envelope, statusCode] = mockReply.mock.calls[0] as [
                unknown,
                ErrorEnvelope,
                number,
            ];

            expect(statusCode).toBe(503);
            expect(envelope).toEqual({
                statusCode: 503,
                code: GENERIC_SERVER_ERROR_CODE,
                message: 'Service Unavailable Exception',
                error: 'Service Unavailable',
                details: readiness,
                path: REQUEST_PATH,
                timestamp: expect.any(String),
                requestId: REQUEST_ID,
            });
        });

        it('adds no details when the body already carries a message', () => {
            sut.catch(new NotFoundException('Item missing'), hostFor(request, response));

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope).not.toHaveProperty('details');
        });

        it('adds no details for a string body', () => {
            sut.catch(
                new ServiceUnavailableException('Daemon unreachable'),
                hostFor(request, response),
            );

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.message).toBe('Daemon unreachable');
            expect(envelope).not.toHaveProperty('details');
        });

        it('publishes a raw string body as the message and adds no details', () => {
            sut.catch(
                new HttpException('Item missing', HttpStatus.NOT_FOUND),
                hostFor(request, response),
            );

            const [, envelope, statusCode] = mockReply.mock.calls[0] as [
                unknown,
                ErrorEnvelope,
                number,
            ];

            expect(statusCode).toBe(404);
            expect(envelope).toEqual({
                statusCode: 404,
                code: GENERIC_CLIENT_ERROR_CODE,
                message: 'Item missing',
                error: 'Not Found',
                path: REQUEST_PATH,
                timestamp: expect.any(String),
                requestId: REQUEST_ID,
            });
        });

        it('adds no details for an array body, which is not a structured payload', () => {
            sut.catch(
                new HttpException(['first', 'second'], HttpStatus.BAD_REQUEST),
                hostFor(request, response),
            );

            const [, envelope, statusCode] = mockReply.mock.calls[0] as [
                unknown,
                ErrorEnvelope,
                number,
            ];

            expect(statusCode).toBe(400);
            expect(envelope).not.toHaveProperty('details');
            expect(envelope.code).toBe(GENERIC_CLIENT_ERROR_CODE);
        });

        it('adds no details for an unexpected error', () => {
            sut.catch(new Error('boom'), hostFor(request, response));

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope).not.toHaveProperty('details');
        });
    });

    describe('error code', () => {
        it('publishes the code of the domain error chained as the exception cause', () => {
            const domainError = new CodedDomainError('SERVICE_NOT_FOUND', 'Service missing');

            sut.catch(
                new NotFoundException(domainError.message, { cause: domainError }),
                hostFor(request, response),
            );

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.code).toBe('SERVICE_NOT_FOUND');
        });

        it('publishes the domain code for a 5xx translated from a domain error too', () => {
            const domainError = new CodedDomainError('PROVIDER_UNAVAILABLE', 'GitHub is unreachable.');

            sut.catch(
                new ServiceUnavailableException(domainError.message, { cause: domainError }),
                hostFor(request, response),
            );

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.code).toBe('PROVIDER_UNAVAILABLE');
        });

        it('falls back to the generic client code for a 4xx with no domain cause', () => {
            sut.catch(new BadRequestException('nope'), hostFor(request, response));

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.code).toBe(GENERIC_CLIENT_ERROR_CODE);
        });

        it('falls back to the generic client code when the cause is not a domain error', () => {
            sut.catch(
                new NotFoundException('missing', { cause: new Error('boom') }),
                hostFor(request, response),
            );

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.code).toBe(GENERIC_CLIENT_ERROR_CODE);
        });

        it('falls back to the generic server code for a 5xx with no domain cause', () => {
            sut.catch(new ServiceUnavailableException('daemon down'), hostFor(request, response));

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.code).toBe(GENERIC_SERVER_ERROR_CODE);
        });

        it('falls back to the generic server code for an unexpected error', () => {
            sut.catch(new Error('boom'), hostFor(request, response));

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.code).toBe(GENERIC_SERVER_ERROR_CODE);
        });

        it('publishes a code for a non-Error thrown value', () => {
            sut.catch('just a string', hostFor(request, response));

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.code).toBe(GENERIC_SERVER_ERROR_CODE);
        });
    });

    describe('request id', () => {
        it('generates one when the request carries no X-Request-Id', () => {
            sut.catch(
                new NotFoundException('Item missing'),
                hostFor({ url: REQUEST_PATH, headers: {} }, response),
            );

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.requestId).toMatch(UUID_PATTERN);
        });

        it('generates one when the request has no headers at all', () => {
            sut.catch(new Error('boom'), hostFor({ url: REQUEST_PATH }, response));

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.requestId).toMatch(UUID_PATTERN);
        });
    });
});
