import {
    ArgumentsHost,
    BadRequestException,
    HttpException,
    HttpStatus,
    NotFoundException,
    ServiceUnavailableException,
} from '@nestjs/common';
import { HttpAdapterHost } from '@nestjs/core';

import { DomainError } from '../../../domain/errors/domain.error';
import type { AppLogger } from '../../../domain/ports/app-logger.port';
import {
    AllExceptionsFilter,
    GENERIC_CLIENT_ERROR_CODE,
    GENERIC_SERVER_ERROR_CODE,
} from '../all-exceptions.filter';

/**
 * Consistent error-envelope shape asserted at the `reply(...)` boundary.
 */
interface ErrorEnvelope {
    statusCode: number;
    code: string;
    message: string | string[];
    error: string;
    details?: object;
    timestamp: string;
    path: string;
    requestId: string;
}

/**
 * Stand-in for a feature domain error, so the specs pin the `cause.code` →
 * envelope `code` half of the contract without depending on a feature.
 */
class CodedDomainError extends DomainError {
    constructor(code: string, message = 'Domain failure') {
        super(code, message);
    }
}

const REQUEST_PATH = '/api/v1/resource';
const REQUEST_ID = 'req-1234';

/** RFC 4122 shape of a correlation id generated by the filter. */
const UUID_PATTERN = /^[\da-f]{8}(?:-[\da-f]{4}){3}-[\da-f]{12}$/;

/**
 * Builds a fake `ArgumentsHost` from `jest.fn()` mocks whose HTTP context hands
 * back the fixture request/response — mirrors the decorator spec's fake
 * `ExecutionContext`.
 */
const hostFor = (
    request: unknown,
    response: unknown,
): ArgumentsHost => {
    const mockGetRequest = jest.fn().mockReturnValue(request);
    const mockGetResponse = jest.fn().mockReturnValue(response);
    const mockSwitchToHttp = jest
        .fn()
        .mockReturnValue({ getRequest: mockGetRequest, getResponse: mockGetResponse });

    return {
        switchToHttp: mockSwitchToHttp,
    } as unknown as ArgumentsHost;
};

describe('AllExceptionsFilter', () => {
    const request = { url: REQUEST_PATH, headers: { 'x-request-id': REQUEST_ID } };
    const response = {};

    let mockReply: jest.Mock;
    let mockGetRequestUrl: jest.Mock;
    let mockHttpAdapterHost: HttpAdapterHost;
    let mockLogger: jest.Mocked<AppLogger>;
    let mockWarn: jest.Mock;
    let mockError: jest.Mock;
    let sut: AllExceptionsFilter;

    beforeEach(() => {
        jest.clearAllMocks();

        mockReply = jest.fn();
        mockGetRequestUrl = jest.fn().mockReturnValue(REQUEST_PATH);

        const httpAdapter: jest.Mocked<Pick<
            HttpAdapterHost['httpAdapter'],
            'getRequestUrl' | 'reply'
        >> = {
            getRequestUrl: mockGetRequestUrl,
            reply: mockReply,
        };

        mockHttpAdapterHost = { httpAdapter } as unknown as HttpAdapterHost;

        mockLogger = {
            debug: jest.fn(), log: jest.fn(), warn: jest.fn(), error: jest.fn(),
        };
        mockWarn = mockLogger.warn as jest.Mock;
        mockError = mockLogger.error as jest.Mock;

        sut = new AllExceptionsFilter(mockHttpAdapterHost, mockLogger);
    });

    afterEach(() => {
        jest.restoreAllMocks();
    });

    it('formats an HttpException into an envelope preserving status code and message', () => {
        sut.catch(new NotFoundException('Item missing'), hostFor(request, response));

        expect(mockReply).toHaveBeenCalledTimes(1);
        const [replyResponse, envelope, statusCode] = mockReply.mock.calls[0] as [
            unknown,
            ErrorEnvelope,
            number,
        ];

        expect(replyResponse).toBe(response);
        expect(statusCode).toBe(404);
        expect(envelope).toEqual({
            statusCode: 404,
            code: GENERIC_CLIENT_ERROR_CODE,
            message: 'Item missing',
            error: 'Not Found',
            path: REQUEST_PATH,
            timestamp: expect.any(String),
            requestId: REQUEST_ID,
        });
        expect(mockWarn).toHaveBeenCalledTimes(1);
        expect(mockWarn).toHaveBeenCalledWith(
            `[${REQUEST_ID}] 404 ${REQUEST_PATH} - Item missing`,
            'AllExceptionsFilter',
        );
        expect(mockError).not.toHaveBeenCalled();
    });

    it('preserves the validation message array from a BadRequestException', () => {
        const validationMessages = ['name must be a string', 'age must be an integer'];

        sut.catch(new BadRequestException(validationMessages), hostFor(request, response));

        expect(mockReply).toHaveBeenCalledTimes(1);
        const [replyResponse, envelope, statusCode] = mockReply.mock.calls[0] as [
            unknown,
            ErrorEnvelope,
            number,
        ];

        expect(replyResponse).toBe(response);
        expect(statusCode).toBe(400);
        expect(envelope).toEqual({
            statusCode: 400,
            code: GENERIC_CLIENT_ERROR_CODE,
            message: validationMessages,
            error: 'Bad Request',
            path: REQUEST_PATH,
            timestamp: expect.any(String),
            requestId: REQUEST_ID,
        });
        expect(Array.isArray(envelope.message)).toBe(true);
        expect(mockWarn).toHaveBeenCalledTimes(1);
        expect(mockWarn).toHaveBeenCalledWith(
            `[${REQUEST_ID}] 400 ${REQUEST_PATH} - ${validationMessages.join(', ')}`,
            'AllExceptionsFilter',
        );
        expect(mockError).not.toHaveBeenCalled();
    });

    it('falls back to a generic error label for a status with no canonical name', () => {
        sut.catch(new HttpException('odd failure', 599), hostFor(request, response));

        const [, envelope, statusCode] = mockReply.mock.calls[0] as [
            unknown,
            ErrorEnvelope,
            number,
        ];

        expect(statusCode).toBe(599);
        expect(envelope.error).toBe('Error');
        expect(envelope.code).toBe(GENERIC_SERVER_ERROR_CODE);
        expect(envelope.requestId).toBe(REQUEST_ID);
    });

    it('returns a generic 500 for an unexpected error without leaking internal details', () => {
        const error = new Error('secret db connection string leaked');

        sut.catch(error, hostFor(request, response));

        expect(mockReply).toHaveBeenCalledTimes(1);
        const [replyResponse, envelope, statusCode] = mockReply.mock.calls[0] as [
            unknown,
            ErrorEnvelope,
            number,
        ];

        expect(replyResponse).toBe(response);
        expect(statusCode).toBe(500);
        expect(envelope).toEqual({
            statusCode: 500,
            code: GENERIC_SERVER_ERROR_CODE,
            message: 'Internal server error',
            error: 'Internal Server Error',
            path: REQUEST_PATH,
            timestamp: expect.any(String),
            requestId: REQUEST_ID,
        });
        expect(JSON.stringify(envelope)).not.toContain('secret db connection string');
    });

    it('logs an unexpected error at error level with the stack as the second argument', () => {
        const error = new Error('secret db connection string leaked');

        sut.catch(error, hostFor(request, response));

        expect(mockError).toHaveBeenCalledTimes(1);
        expect(mockWarn).not.toHaveBeenCalled();
        expect(mockError).toHaveBeenCalledWith(
            `[${REQUEST_ID}] Unhandled exception on 500 ${REQUEST_PATH}`,
            error.stack,
            'AllExceptionsFilter',
        );
        expect(mockError.mock.calls[0][1]).toBe(error.stack);
        expect(mockError.mock.calls[0][2]).toBe('AllExceptionsFilter');
    });

    it('logs a non-Error thrown value at error level with an undefined stack', () => {
        sut.catch('just a string', hostFor(request, response));

        expect(mockError).toHaveBeenCalledTimes(1);
        expect(mockWarn).not.toHaveBeenCalled();
        expect(mockError).toHaveBeenCalledWith(
            `[${REQUEST_ID}] Unhandled exception on 500 ${REQUEST_PATH}`,
            undefined,
            'AllExceptionsFilter',
        );
    });

    describe('logged stack', () => {
        it('appends the stack of the chained cause, which the controller no longer logs', () => {
            const original = new Error('ECONNREFUSED 127.0.0.1:2375');
            const exception = new ServiceUnavailableException('Could not reach the daemon', { cause: original });

            sut.catch(exception, hostFor(request, response));

            const stack = mockError.mock.calls[0][1] as string;

            expect(stack).toContain(exception.stack!);
            expect(stack).toContain('Caused by:');
            expect(stack).toContain('ECONNREFUSED 127.0.0.1:2375');
        });

        it('follows the whole cause chain, so the root failure is never lost', () => {
            const root = new Error('socket hang up');
            const domainError = new CodedDomainError('SOURCE_CONTROL_UNAVAILABLE');

            Object.defineProperty(domainError, 'cause', { value: root });

            sut.catch(
                new ServiceUnavailableException(domainError.message, { cause: domainError }),
                hostFor(request, response),
            );

            const stack = mockError.mock.calls[0][1] as string;

            expect(stack).toContain('Domain failure');
            expect(stack).toContain('socket hang up');
        });

        it('logs exactly one line per failure', () => {
            sut.catch(
                new ServiceUnavailableException('down', { cause: new Error('boom') }),
                hostFor(request, response),
            );

            expect(mockError).toHaveBeenCalledTimes(1);
            expect(mockWarn).not.toHaveBeenCalled();
        });

        it('stops on a cyclic cause chain', () => {
            const first = new Error('first');
            const second = new Error('second', { cause: first });

            Object.defineProperty(first, 'cause', { value: second });

            sut.catch(second, hostFor(request, response));

            expect(mockError.mock.calls[0][1] as string).toContain('first');
        });

        it('keeps the cause out of the client envelope', () => {
            sut.catch(
                new ServiceUnavailableException('Could not reach the daemon', {
                    cause: new Error('ECONNREFUSED 127.0.0.1:2375'),
                }),
                hostFor(request, response),
            );

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(JSON.stringify(envelope)).not.toContain('ECONNREFUSED');
        });
    });

    describe('structured exception bodies', () => {
        it('keeps an object payload under details instead of dropping it', () => {
            const readiness = {
                status: 'error',
                dependencies: [
                    { name: 'database', status: 'up' },
                    { name: 'docker', status: 'down' },
                ],
            };

            sut.catch(new ServiceUnavailableException(readiness), hostFor(request, response));

            const [, envelope, statusCode] = mockReply.mock.calls[0] as [
                unknown,
                ErrorEnvelope,
                number,
            ];

            expect(statusCode).toBe(503);
            expect(envelope).toEqual({
                statusCode: 503,
                code: GENERIC_SERVER_ERROR_CODE,
                message: 'Service Unavailable Exception',
                error: 'Service Unavailable',
                details: readiness,
                path: REQUEST_PATH,
                timestamp: expect.any(String),
                requestId: REQUEST_ID,
            });
        });

        it('adds no details when the body already carries a message', () => {
            sut.catch(new NotFoundException('Item missing'), hostFor(request, response));

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope).not.toHaveProperty('details');
        });

        it('adds no details for a string body', () => {
            sut.catch(
                new ServiceUnavailableException('Daemon unreachable'),
                hostFor(request, response),
            );

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.message).toBe('Daemon unreachable');
            expect(envelope).not.toHaveProperty('details');
        });

        it('publishes a raw string body as the message and adds no details', () => {
            sut.catch(
                new HttpException('Item missing', HttpStatus.NOT_FOUND),
                hostFor(request, response),
            );

            const [, envelope, statusCode] = mockReply.mock.calls[0] as [
                unknown,
                ErrorEnvelope,
                number,
            ];

            expect(statusCode).toBe(404);
            expect(envelope).toEqual({
                statusCode: 404,
                code: GENERIC_CLIENT_ERROR_CODE,
                message: 'Item missing',
                error: 'Not Found',
                path: REQUEST_PATH,
                timestamp: expect.any(String),
                requestId: REQUEST_ID,
            });
        });

        it('adds no details for an array body, which is not a structured payload', () => {
            sut.catch(
                new HttpException(['first', 'second'], HttpStatus.BAD_REQUEST),
                hostFor(request, response),
            );

            const [, envelope, statusCode] = mockReply.mock.calls[0] as [
                unknown,
                ErrorEnvelope,
                number,
            ];

            expect(statusCode).toBe(400);
            expect(envelope).not.toHaveProperty('details');
            expect(envelope.code).toBe(GENERIC_CLIENT_ERROR_CODE);
        });

        it('adds no details for an unexpected error', () => {
            sut.catch(new Error('boom'), hostFor(request, response));

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope).not.toHaveProperty('details');
        });
    });

    describe('error code', () => {
        it('publishes the code of the domain error chained as the exception cause', () => {
            const domainError = new CodedDomainError('SERVICE_NOT_FOUND', 'Service missing');

            sut.catch(
                new NotFoundException(domainError.message, { cause: domainError }),
                hostFor(request, response),
            );

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.code).toBe('SERVICE_NOT_FOUND');
        });

        it('publishes the domain code for a 5xx translated from a domain error too', () => {
            const domainError = new CodedDomainError('SOURCE_CONTROL_UNAVAILABLE', 'GitHub is unreachable.');

            sut.catch(
                new ServiceUnavailableException(domainError.message, { cause: domainError }),
                hostFor(request, response),
            );

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.code).toBe('SOURCE_CONTROL_UNAVAILABLE');
        });

        it('falls back to the generic client code for a 4xx with no domain cause', () => {
            sut.catch(new BadRequestException('nope'), hostFor(request, response));

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.code).toBe(GENERIC_CLIENT_ERROR_CODE);
        });

        it('falls back to the generic client code when the cause is not a domain error', () => {
            sut.catch(
                new NotFoundException('missing', { cause: new Error('boom') }),
                hostFor(request, response),
            );

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.code).toBe(GENERIC_CLIENT_ERROR_CODE);
        });

        it('falls back to the generic server code for a 5xx with no domain cause', () => {
            sut.catch(new ServiceUnavailableException('daemon down'), hostFor(request, response));

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.code).toBe(GENERIC_SERVER_ERROR_CODE);
        });

        it('falls back to the generic server code for an unexpected error', () => {
            sut.catch(new Error('boom'), hostFor(request, response));

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.code).toBe(GENERIC_SERVER_ERROR_CODE);
        });

        it('publishes a code for a non-Error thrown value', () => {
            sut.catch('just a string', hostFor(request, response));

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.code).toBe(GENERIC_SERVER_ERROR_CODE);
        });
    });

    describe('request id', () => {
        it('generates one when the request carries no X-Request-Id', () => {
            sut.catch(
                new NotFoundException('Item missing'),
                hostFor({ url: REQUEST_PATH, headers: {} }, response),
            );

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.requestId).toMatch(UUID_PATTERN);
            expect(mockWarn).toHaveBeenCalledWith(
                `[${envelope.requestId}] 404 ${REQUEST_PATH} - Item missing`,
                'AllExceptionsFilter',
            );
        });

        it('generates one when the request has no headers at all', () => {
            sut.catch(new Error('boom'), hostFor({ url: REQUEST_PATH }, response));

            const [, envelope] = mockReply.mock.calls[0] as [unknown, ErrorEnvelope, number];

            expect(envelope.requestId).toMatch(UUID_PATTERN);
        });
    });
});
