import { Inject, Injectable } from '@nestjs/common';

import { getNetworksByServiceUseCase } from '../../application/get-networks-by-service.use-case';
import { ServiceNotFoundError } from '../../domain/errors/network.errors';
import { Network } from '../../domain/models/network.models';
import type { NetworksRepository } from '../../domain/repositories/networks.repository';
import { DockerNetworksRepository } from '../../infrastructure/docker/docker-networks.repository';

import type { ServicesRepository } from '@features/services/domain/repositories/services.repository';
import { DatabaseServicesRepository } from '@features/services/infrastructure/database/db-services.repository';

/**
 * Networks service
 */
@Injectable()
export class NetworksService {
    constructor(
        @Inject(DatabaseServicesRepository)
        private readonly servicesRepository: ServicesRepository,
        @Inject(DockerNetworksRepository)
        private readonly networksRepository: NetworksRepository,
    ) {}

    /**
     * List the Docker networks generated by a service's compose stack.
     *
     * @param serviceId Service identifier
     *
     * @returns Networks of the service
     *
     * @throws {ServiceNotFoundError} When the service does not exist
     */
    public async getByService(serviceId: string): Promise<Network[]> {
        const service = await this.servicesRepository.findById(serviceId);

        if (!service) {
            throw new ServiceNotFoundError(serviceId);
        }

        return getNetworksByServiceUseCase(this.networksRepository, service);
    }
}
