import { Inject, Injectable, NotFoundException } from '@nestjs/common';

import { getNetworksByServiceUseCase } from '../../application/get-networks-by-service.use-case';
import { Network } from '../../domain/models/network.model';
import type { NetworksRepository } from '../../domain/repositories/networks.repository';
import { DockerNetworksRepository } from '../../infrastructure/docker/docker-networks.repository';

import type { ServicesRepository } from '@features/services/domain/repositories/services.repository';
import { ServicesDatabaseRepository } from '@features/services/infrastructure/database/services-db.repository';

/**
 * Networks service
 */
@Injectable()
export class NetworksService {
    constructor(
        @Inject(ServicesDatabaseRepository)
        private readonly servicesRepository: ServicesRepository,
        @Inject(DockerNetworksRepository)
        private readonly networksRepository: NetworksRepository,
    ) {}

    /**
     * List the Docker networks generated by a service's compose stack.
     *
     * @param serviceId Service identifier
     *
     * @returns Networks of the service
     */
    public async getByService(serviceId: string): Promise<Network[]> {
        const service = await this.servicesRepository.findById(serviceId);

        if (!service) {
            throw new NotFoundException(`Service ${serviceId} not found`);
        }

        return getNetworksByServiceUseCase(this.networksRepository, service);
    }
}
