import { Container } from '../models/container.model';

import { Service } from '@features/services/domain/models/service.model';

/**
 * Containers repository
 */
export interface ContainersRepository {
    /**
     * List every container generated by a service
     *
     * @param service Service the containers belong to
     *
     * @returns Containers of the service
     */
    listByService: (service: Service) => Promise<Container[]>;
}
