import { DatePipe } from '@angular/common';
import { Component, input } from '@angular/core';

import { Network } from '../../../domain/models/network.model';

import { ComponentCardComponent } from '@shared/components/component-card/component-card.component';

@Component({
    selector: 'app-service-networks',
    templateUrl: './service-networks.component.html',
    imports: [ComponentCardComponent, DatePipe],
})

/**
 * Presentational card listing, as a table, the Docker networks generated by a
 * service's compose stack.
 */
export class ServiceNetworksComponent {
    /**
     * Networks of the service.
     */
    public readonly networks = input<Network[]>([]);

    /**
     * Whether the network list is loading.
     */
    public readonly loading = input(false);
}
