import { Network } from '../domain/models/network.model';
import { NetworksRepository } from '../domain/repositories/networks.repository';

import { Service } from '@features/services/domain/models/service.model';

/**
 * Use case for listing every network generated by a service
 *
 * @param repository Networks repository
 * @param service Service the networks belong to
 *
 * @returns Networks of the service
 */
export function getNetworksByServiceUseCase(repository: NetworksRepository, service: Service): Promise<Network[]> {
    return repository.listByService(service);
}
