import { Network } from '../domain/models/network.models';
import { NetworksRepository } from '../domain/repositories/networks.repository';

import { ServiceNotFoundError } from '@features/services/domain/errors/service.errors';
import { ServicesRepository } from '@features/services/domain/repositories/services.repository';

/**
 * Use case for listing every network generated by a service
 *
 * Resolving the service is part of the business step, so the domain error is
 * raised here — the UI edge only translates it into a status code.
 *
 * @param servicesRepository Services repository
 * @param networksRepository Networks repository
 * @param serviceId Identifier of the service the networks belong to
 *
 * @returns Networks of the service
 *
 * @throws {ServiceNotFoundError} When the service does not exist
 */
export async function getNetworksByServiceUseCase(
    servicesRepository: ServicesRepository,
    networksRepository: NetworksRepository,
    serviceId: string,
): Promise<Network[]> {
    const service = await servicesRepository.findById(serviceId);

    if (!service) {
        throw new ServiceNotFoundError(serviceId);
    }

    return networksRepository.listByService(service);
}
