import { httpResource } from '@angular/common/http';
import { Injectable } from '@angular/core';

import { Container } from '../../domain/models/container.model';

import { environment } from '@environments/environment';

@Injectable()

/**
 * Containers API repository
 */
export class ContainersApiRepository {
    private readonly url = `${environment.apiBaseUrl}/containers`;

    /**
     * Resource with the Docker containers generated by a service
     *
     * @param serviceId Accessor returning the service identifier
     *
     * @returns Resource that resolves to the service's containers
     */
    public containersByService(serviceId: () => string | undefined) {
        return httpResource<Container[]>(() => {
            const id = serviceId();

            return id ? `${this.url}?serviceId=${id}` : undefined;
        });
    }
}
