import { Injectable } from '@nestjs/common';
import Docker from 'dockerode';

import { Container } from '../../domain/models/container.model';
import { ContainersRepository } from '../../domain/repositories/containers.repository';

import { DockerClient } from '@core/infrastructure/docker/docker.client';
import { Service } from '@features/services/domain/models/service.model';

/**
 * Compose label Docker stamps on every container it groups under a service's stack.
 */
const COMPOSE_PROJECT_LABEL = 'com.docker.compose.project';

/**
 * Builds the Docker Compose project name for a service from its name, falling
 * back to its id. This value groups all of the service's Docker resources under
 * the `com.docker.compose.project` label.
 *
 * @param service Service to derive the project name from
 *
 * @returns Compose project name
 */
function composeProjectName(service: Service): string {
    const slug = service.name.toLowerCase().replace(/[^\da-z]+/g, '-').replace(/^-+|-+$/g, '');

    return slug || `service-${service.id}`;
}

/**
 * Docker containers repository
 *
 * Obtains a Dockerode instance from the core `DockerClient` and lists a
 * service's containers, normalizing the daemon payload. The mapping from a
 * service to its compose project label is kept here as an infrastructure detail.
 */
@Injectable()
export class DockerContainersRepository implements ContainersRepository {
    constructor(private readonly client: DockerClient) {}

    /**
     * List every container generated by a service, running or not.
     *
     * @param service Service the containers belong to
     *
     * @returns Containers of the service
     */
    public async listByService(service: Service): Promise<Container[]> {
        const containers = await this.client.getClient().listContainers({
            all: true,
            filters: { label: [`${COMPOSE_PROJECT_LABEL}=${composeProjectName(service)}`] },
        });

        return containers.map((container) => this.toContainer(container));
    }

    /**
     * Narrows a Dockerode container summary into the domain model.
     *
     * @param info Dockerode container summary
     *
     * @returns Normalized container
     */
    private toContainer(info: Docker.ContainerInfo): Container {
        return {
            id: info.Id,
            name: info.Names?.[0]?.replace(/^\//, '') ?? info.Id.slice(0, 12),
            image: info.Image,
            state: info.State,
            status: info.Status,
            createdAt: new Date(info.Created * 1000),
            ports: (info.Ports ?? []).map((port) => ({
                privatePort: port.PrivatePort,
                publicPort: port.PublicPort ?? null,
                type: port.Type,
            })),
        };
    }
}
