import { Inject, Injectable, NotFoundException } from '@nestjs/common';

import { getContainersByServiceUseCase } from '../../application/get-containers-by-service.use-case';
import { Container } from '../../domain/models/container.model';
import { DockerContainersRepository } from '../../infrastructure/docker/docker-containers.repository';

import { ServicesDatabaseRepository } from '@features/services/infrastructure/database/services-db.repository';

@Injectable()

/**
 * Containers service
 */
export class ContainersService {
    constructor(
        @Inject(ServicesDatabaseRepository)
        private readonly servicesRepository: ServicesDatabaseRepository,
        @Inject(DockerContainersRepository)
        private readonly containersRepository: DockerContainersRepository,
    ) {}

    /**
     * List the Docker containers generated by a service's compose stack.
     *
     * @param serviceId Service identifier
     *
     * @returns Containers of the service
     */
    public async getByService(serviceId: string): Promise<Container[]> {
        const service = await this.servicesRepository.findById(serviceId);

        if (!service) {
            throw new NotFoundException(`Service ${serviceId} not found`);
        }

        return getContainersByServiceUseCase(this.containersRepository, service);
    }
}
