import { Inject, Injectable } from '@nestjs/common';

import { getContainersByServiceUseCase } from '../../application/get-containers-by-service.use-case';
import { ServiceNotFoundError } from '../../domain/errors/container.errors';
import { Container } from '../../domain/models/container.models';
import type { ContainersRepository } from '../../domain/repositories/containers.repository';
import { DockerContainersRepository } from '../../infrastructure/docker/docker-containers.repository';

import type { ServicesRepository } from '@features/services/domain/repositories/services.repository';
import { DatabaseServicesRepository } from '@features/services/infrastructure/database/db-services.repository';

/**
 * Containers service
 */
@Injectable()
export class ContainersService {
    constructor(
        @Inject(DatabaseServicesRepository)
        private readonly servicesRepository: ServicesRepository,
        @Inject(DockerContainersRepository)
        private readonly containersRepository: ContainersRepository,
    ) {}

    /**
     * List the Docker containers generated by a service's compose stack.
     *
     * @param serviceId Service identifier
     *
     * @returns Containers of the service
     *
     * @throws {ServiceNotFoundError} When the service does not exist
     */
    public async getByService(serviceId: string): Promise<Container[]> {
        const service = await this.servicesRepository.findById(serviceId);

        if (!service) {
            throw new ServiceNotFoundError(serviceId);
        }

        return getContainersByServiceUseCase(this.containersRepository, service);
    }
}
