import { Injectable } from '@nestjs/common';

import { Network } from '../../domain/models/network.model';
import { NetworksRepository } from '../../domain/repositories/networks.repository';

import { toNetwork } from './docker-networks.transformer';

import { DockerClient } from '@core/infrastructure/docker/docker.client';
import { Service } from '@features/services/domain/models/service.model';

/**
 * Compose label Docker stamps on every network it groups under a service's stack.
 */
const COMPOSE_PROJECT_LABEL = 'com.docker.compose.project';

/**
 * Builds the Docker Compose project name for a service from its name, falling
 * back to its id. This value groups all of the service's Docker resources under
 * the `com.docker.compose.project` label.
 *
 * @param service Service to derive the project name from
 *
 * @returns Compose project name
 */
function composeProjectName(service: Service): string {
    const slug = service.name.toLowerCase().replace(/[^\da-z]+/g, '-').replace(/^-+|-+$/g, '');

    return slug || `service-${service.id}`;
}

/**
 * Docker networks repository
 *
 * Obtains a Dockerode instance from the core `DockerClient` and lists a
 * service's networks, normalizing the daemon payload. The mapping from a
 * service to its compose project label is kept here as an infrastructure detail.
 */
@Injectable()
export class DockerNetworksRepository implements NetworksRepository {
    constructor(private readonly client: DockerClient) {}

    /**
     * List every network generated by a service.
     *
     * @param service Service the networks belong to
     *
     * @returns Networks of the service
     */
    public async listByService(service: Service): Promise<Network[]> {
        const networks = await this.client.getClient().listNetworks({
            filters: { label: [`${COMPOSE_PROJECT_LABEL}=${composeProjectName(service)}`] },
        });

        return networks.map(toNetwork);
    }
}
