import { httpResource } from '@angular/common/http';
import { Injectable } from '@angular/core';

import { Network } from '../../domain/models/network.model';

import { environment } from '@environments/environment';

@Injectable()

/**
 * Networks API repository
 */
export class NetworksApiRepository {
    private readonly url = `${environment.apiBaseUrl}/networks`;

    /**
     * Resource with the Docker networks generated by a service
     *
     * @param serviceId Accessor returning the service identifier
     *
     * @returns Resource that resolves to the service's networks
     */
    public networksByService(serviceId: () => string | undefined) {
        return httpResource<Network[]>(() => {
            const id = serviceId();

            return id ? `${this.url}?serviceId=${id}` : undefined;
        });
    }
}
