import { HttpClient, httpResource } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import type {
    CreateProjectNetworkDto,
    JoinProjectNetworkDto,
    Network,
    ProjectNetwork,
    UpdateProjectNetworkDto,
} from '@gitpaas/contracts';
import { Observable } from 'rxjs';

import { environment } from '@environments/environment';

@Injectable()

/**
 * Networks API repository
 */
export class NetworksApiRepository {
    private readonly http = inject(HttpClient);

    private readonly url = `${environment.apiBaseUrl}/networks`;

    private readonly projectsUrl = `${environment.apiBaseUrl}/projects`;

    /**
     * Resource with the Docker networks generated by a service
     *
     * @param serviceId Accessor returning the service identifier
     *
     * @returns Resource that resolves to the service's networks
     */
    public networksByService(serviceId: () => string | undefined) {
        return httpResource<Network[]>(() => {
            const id = serviceId();

            return id ? `${this.url}?serviceId=${id}` : undefined;
        });
    }

    /**
     * Resource with the networks a project owns
     *
     * @param projectId Accessor returning the project identifier
     *
     * @returns Resource that resolves to the networks of the project
     */
    public networksByProject(projectId: () => string | undefined) {
        return httpResource<ProjectNetwork[]>(() => {
            const id = projectId();

            return id ? this.projectNetworksUrl(id) : undefined;
        });
    }

    /**
     * Creates a network inside a project
     *
     * @param projectId Project identifier
     * @param dto Display name of the new network
     *
     * @returns Created network
     */
    public createProjectNetwork(projectId: string, dto: CreateProjectNetworkDto): Observable<ProjectNetwork> {
        return this.http.post<ProjectNetwork>(this.projectNetworksUrl(projectId), dto);
    }

    /**
     * Renames a network the project already holds
     *
     * @param projectId Project identifier
     * @param id Network identifier
     * @param dto New display name of the network
     *
     * @returns Renamed network
     */
    public renameProjectNetwork(
        projectId: string,
        id: string,
        dto: UpdateProjectNetworkDto,
    ): Observable<ProjectNetwork> {
        return this.http.put<ProjectNetwork>(`${this.projectNetworksUrl(projectId)}/${id}`, dto);
    }

    /**
     * Removes a network of a project
     *
     * @param projectId Project identifier
     * @param id Network identifier
     */
    public removeProjectNetwork(projectId: string, id: string): Observable<void> {
        // eslint-disable-next-line @typescript-eslint/no-invalid-void-type
        return this.http.delete<void>(`${this.projectNetworksUrl(projectId)}/${id}`);
    }

    /**
     * Joins a service to a network of its project
     *
     * @param projectId Project identifier
     * @param id Network identifier
     * @param dto Service that joins the network
     */
    public joinProjectNetwork(projectId: string, id: string, dto: JoinProjectNetworkDto): Observable<void> {
        // eslint-disable-next-line @typescript-eslint/no-invalid-void-type
        return this.http.post<void>(`${this.projectNetworksUrl(projectId)}/${id}/services`, dto);
    }

    /**
     * Builds the networks collection URL of a project
     *
     * @param projectId Project identifier
     *
     * @returns Networks collection URL of that project
     */
    private projectNetworksUrl(projectId: string): string {
        return `${this.projectsUrl}/${projectId}/networks`;
    }
}
