import { Container } from '../domain/models/container.models';
import { ContainersRepository } from '../domain/repositories/containers.repository';

import { ServiceNotFoundError } from '@features/services/domain/errors/service.errors';
import { ServicesRepository } from '@features/services/domain/repositories/services.repository';

/**
 * Use case for listing every container generated by a service.
 *
 * @param servicesRepository Services repository
 * @param containersRepository Containers repository
 * @param serviceId Identifier of the service the containers belong to
 *
 * @returns Containers of the service
 */
export async function getContainersByServiceUseCase(
    servicesRepository: ServicesRepository,
    containersRepository: ContainersRepository,
    serviceId: string,
): Promise<Container[]> {
    const service = await servicesRepository.findById(serviceId);

    if (!service) {
        throw new ServiceNotFoundError(serviceId);
    }

    return containersRepository.listByService(service);
}
