import { Container } from '../domain/models/container.model';
import { ContainersRepository } from '../domain/repositories/containers.repository';

import { Service } from '@features/services/domain/models/service.model';

/**
 * Use case for listing every container generated by a service
 *
 * @param repository Containers repository
 * @param service Service the containers belong to
 *
 * @returns Containers of the service
 */
export function getContainersByServiceUseCase(repository: ContainersRepository, service: Service): Promise<Container[]> {
    return repository.listByService(service);
}
