import type { Network as NetworkResponse } from '@gitpaas/contracts';
import { Controller, Get, ParseUUIDPipe, Query, ServiceUnavailableException } from '@nestjs/common';

import { NetworksService } from '../services/networks.service';
import { toNetworkResponse } from '../transformers/network-response.transformer';

import { DaemonUnreachableError } from '@core/domain/errors/container-runtime.errors';
import { enrichTelemetry } from '@core/infrastructure/telemetry/telemetry.context';
import { translateError } from '@core/ui/translators/http-error.translator';

/**
 * Networks controller
 */
@Controller('networks')
export class NetworksController {
    constructor(private readonly service: NetworksService) {}

    /**
     * List the Docker networks generated by a service's compose stack.
     *
     * @param serviceId Service identifier
     *
     * @returns Networks of the service
     */
    @Get()
    public async getByService(@Query('serviceId', ParseUUIDPipe) serviceId: string): Promise<NetworkResponse[]> {
        enrichTelemetry({ 'service.id': serviceId });

        try {
            const networks = await this.service.getByService(serviceId);

            return networks.map(toNetworkResponse);
        } catch (error) {
            if (error instanceof DaemonUnreachableError) {
                throw new ServiceUnavailableException(
                    'Could not reach the server Docker daemon. Verify the server is running and reachable.',
                    { cause: error },
                );
            }

            throw translateError(error);
        }
    }
}
