import { Controller, Get, ParseUUIDPipe, Query, ServiceUnavailableException } from '@nestjs/common';

import { Network } from '../../domain/models/network.models';
import { NetworksService } from '../services/networks.service';

import { translateError } from '@core/ui/translators/http-error.translator';

/**
 * Networks controller
 */
@Controller('networks')
export class NetworksController {
    constructor(private readonly service: NetworksService) {}

    /**
     * List the Docker networks generated by a service's compose stack.
     *
     * @param serviceId Service identifier
     *
     * @returns Networks of the service
     */
    @Get()
    public async getByService(@Query('serviceId', ParseUUIDPipe) serviceId: string): Promise<Network[]> {
        try {
            return await this.service.getByService(serviceId);
        } catch (error) {
            throw translateError(error, () => new ServiceUnavailableException(
                'Could not reach the server Docker daemon. Verify the server is running and reachable',
                { cause: error },
            ));
        }
    }
}
