import { Controller, Get, NotFoundException, ParseUUIDPipe, Query, ServiceUnavailableException } from '@nestjs/common';

import { Network } from '../../domain/models/network.model';
import { NetworksService } from '../services/networks.service';

import { DiagnosticLoggerService } from '@core/ui/services/diagnostic-logger.service';

/**
 * Networks controller
 */
@Controller('networks')
export class NetworksController {
    constructor(
        private readonly service: NetworksService,
        private readonly diagnostics: DiagnosticLoggerService,
    ) {}

    /**
     * List the Docker networks generated by a service's compose stack.
     *
     * @param serviceId Service identifier
     *
     * @returns Networks of the service
     */
    @Get()
    public async getByService(@Query('serviceId', ParseUUIDPipe) serviceId: string): Promise<Network[]> {
        try {
            return await this.service.getByService(serviceId);
        } catch (error) {
            if (error instanceof NotFoundException || error instanceof ServiceUnavailableException) {
                throw error;
            }

            this.diagnostics.error(`Failed to list networks for service ${serviceId}`, error, NetworksController.name);

            throw new ServiceUnavailableException(
                'Could not reach the VPS Docker daemon. Verify the VPS is running and reachable; '
                    + 'in local development, start the emulated VPS (see CONTRIBUTING.md).',
            );
        }
    }
}
