import { DatePipe } from '@angular/common';
import { Component, input } from '@angular/core';

import { Container, ContainerPort } from '../../../domain/models/container.model';

import { ComponentCardComponent } from '@shared/components/component-card/component-card.component';

@Component({
    selector: 'app-service-containers',
    templateUrl: './service-containers.component.html',
    imports: [ComponentCardComponent, DatePipe],
})

/**
 * Presentational card listing, as a table, the Docker containers generated by a
 * service's compose stack.
 */
export class ServiceContainersComponent {
    /**
     * Containers of the service.
     */
    public readonly containers = input<Container[]>([]);

    /**
     * Whether the container list is loading.
     */
    public readonly loading = input(false);

    /**
     * Colour classes for a container state badge.
     *
     * @param state Container lifecycle state
     *
     * @returns Tailwind classes for the badge
     */
    protected stateBadgeClass(state: string): string {
        switch (state) {
            case 'running':
                return 'bg-success-50 text-success-600 dark:bg-success-500/15 dark:text-success-500';
            case 'exited':
            case 'dead':
                return 'bg-error-50 text-error-600 dark:bg-error-500/15 dark:text-error-500';
            case 'paused':
            case 'restarting':
                return 'bg-warning-50 text-warning-600 dark:bg-warning-500/15 dark:text-warning-500';
            default:
                return 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400';
        }
    }

    /**
     * Formats a container's published ports as a compact string.
     *
     * @param ports Container port mappings
     *
     * @returns Ports such as `8080:3000/tcp, 5432/tcp`, or a placeholder when none
     */
    protected formatPorts(ports: ContainerPort[]): string {
        if (ports.length === 0) {
            return '—';
        }

        return ports
            .map((port) => `${port.publicPort ? `${port.publicPort}:` : ''}${port.privatePort}/${port.type}`)
            .join(', ');
    }
}
