import { Controller, Get, NotFoundException, ParseUUIDPipe, Query, ServiceUnavailableException } from '@nestjs/common';

import { Container } from '../../domain/models/container.model';
import { ContainersService } from '../services/containers.service';

import { DiagnosticLoggerService } from '@core/ui/services/diagnostic-logger.service';

/**
 * Containers controller
 */
@Controller('containers')
export class ContainersController {
    constructor(
        private readonly service: ContainersService,
        private readonly diagnostics: DiagnosticLoggerService,
    ) {}

    /**
     * List the Docker containers generated by a service's compose stack.
     *
     * @param serviceId Service identifier
     *
     * @returns Containers of the service
     */
    @Get()
    public async getByService(@Query('serviceId', ParseUUIDPipe) serviceId: string): Promise<Container[]> {
        try {
            return await this.service.getByService(serviceId);
        } catch (error) {
            if (error instanceof NotFoundException || error instanceof ServiceUnavailableException) {
                throw error;
            }

            this.diagnostics.error(`Failed to list containers for service ${serviceId}`, error, ContainersController.name);

            throw new ServiceUnavailableException(
                'Could not reach the VPS Docker daemon. Verify the VPS is running and reachable; '
                    + 'in local development, start the emulated VPS (see CONTRIBUTING.md).',
            );
        }
    }
}
