import { Controller, Get, Inject, NotFoundException, ParseUUIDPipe, Query, ServiceUnavailableException } from '@nestjs/common';

import { ServiceNotFoundError } from '../../domain/errors/container.errors';
import { Container } from '../../domain/models/container.models';
import { ContainersService } from '../services/containers.service';

import type { AppLogger } from '@core/domain/ports/app-logger.port';
import { NestLoggerAdapter } from '@core/infrastructure/logging/nest-logger.adapter';

/**
 * Containers controller
 */
@Controller('containers')
export class ContainersController {
    constructor(
        private readonly service: ContainersService,
        @Inject(NestLoggerAdapter) private readonly logger: AppLogger,
    ) {}

    /**
     * List the Docker containers generated by a service's compose stack.
     *
     * @param serviceId Service identifier
     *
     * @returns Containers of the service
     */
    @Get()
    public async getByService(@Query('serviceId', ParseUUIDPipe) serviceId: string): Promise<Container[]> {
        try {
            return await this.service.getByService(serviceId);
        } catch (error) {
            if (error instanceof ServiceNotFoundError) {
                throw new NotFoundException(error.message);
            }

            if (error instanceof ServiceUnavailableException) {
                throw error;
            }

            this.logger.error(`Failed to list containers for service ${serviceId}`, error, ContainersController.name);

            throw new ServiceUnavailableException(
                'Could not reach the server Docker daemon. Verify the server is running and reachable; '
                    + 'in local development, start the emulated server (see CONTRIBUTING.md).',
            );
        }
    }
}
