import { Controller, Get, ParseUUIDPipe, Query, ServiceUnavailableException } from '@nestjs/common';

import { Container } from '../../domain/models/container.models';
import { ContainersService } from '../services/containers.service';

import { translateError } from '@core/ui/translators/http-error.translator';

/**
 * Containers controller
 */
@Controller('containers')
export class ContainersController {
    constructor(private readonly service: ContainersService) {}

    /**
     * List the Docker containers generated by a service's compose stack.
     *
     * The failure is not logged here: the exception thrown carries the original
     * error as its `cause`, and the global exception filter writes the single log
     * line for it — the only one that also carries the request id.
     *
     * @param serviceId Service identifier
     *
     * @returns Containers of the service
     */
    @Get()
    public async getByService(@Query('serviceId', ParseUUIDPipe) serviceId: string): Promise<Container[]> {
        try {
            return await this.service.getByService(serviceId);
        } catch (error) {
            throw translateError(error, () => new ServiceUnavailableException(
                'Could not reach the server Docker daemon. Verify the server is running and reachable; '
                    + 'in local development, start the emulated server (see CONTRIBUTING.md).',
                { cause: error },
            ));
        }
    }
}
