/**
 * A Docker network generated by a service's compose stack.
 */
export interface Network {
    id: string;
    name: string;
    driver: string;
    scope: string;
    internal: boolean;
    attachable: boolean;
    createdAt: Date;
}
