/**
 * Where a network of a service stands.
 */
export type NetworkState = 'attached' | 'declared' | 'connected' | 'joining' | 'leaving';

/**
 * A network generated by a service's stack.
 */
export interface Network {
    id: string;
    name: string;
    driver?: string;
    scope?: string;
    internal?: boolean;
    attachable?: boolean;
    createdAt?: Date;
}

/**
 * A network of a service, together with the state the two reads of the daemon give it.
 */
export interface NetworkStatus extends Network {
    state: NetworkState;
}
