/**
 * A Docker network generated by a service's compose stack.
 */
export interface Network {
    id: string;
    name: string;
    /** Network driver, e.g. `bridge` or `overlay`. */
    driver: string;
    /** Network scope, e.g. `local` or `swarm`. */
    scope: string;
    /** Whether the network is internal (not exposed to the host). */
    internal: boolean;
    /** Whether standalone containers can attach to the network. */
    attachable: boolean;
    createdAt: string;
}
