import { Network } from '../models/network.models';

import { Service } from '@features/services/domain/models/service.models';

/**
 * Networks repository
 */
export interface NetworksRepository {
    /**
     * List every network generated by a service.
     *
     * @param service Service the networks belong to
     *
     * @returns Networks of the service
     */
    listByService: (service: Service) => Promise<Network[]>;
}
