import { Network } from '../models/network.models';

import { Service } from '@features/services/domain/models/service.models';

/**
 * Networks repository
 */
export interface NetworksRepository {
    /**
     * List every network generated by a service.
     *
     * @param service Service the networks belong to
     *
     * @returns Networks of the service
     */
    listByService: (service: Service) => Promise<Network[]>;

    /**
     * List every network the containers of a service hold.
     *
     * @param service Service the containers belong to
     *
     * @returns Networks the containers of the service are connected to
     */
    listConnectedByService: (service: Service) => Promise<Network[]>;
}
