name: PR Labeler

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  label:
    name: Apply kind label
    runs-on: ubuntu-latest
    steps:
      - name: Label pull request from its branch type
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          sync-labels: true
